service: 'aws-lambda-performance-tests'

provider:
    name: 'aws'
    runtime: 'java11'
    region: '${self:custom.region}'
    stage: '${self:custom.stage}'
    memorySize: '1024'
    timeout: '60'
    
    iamRoleStatements:
        -   Effect: 'Allow'
            Action:
                - 'lambda:InvokeFunction'
            Resource:
                - '${self:custom.lambda.lambdaTestTarget.arn}'

plugins:
    - 'serverless-plugin-log-retention'

custom:
    version: '1.0.0-SNAPSHOT'
    logRetentionInDays: '3'
    accountId: '${env:AWS_ACCOUNT_ID}'
    region: 'eu-west-1'
    stage: '${opt:stage, ''dev''}'
    
    lambda:
        lambdaTestTarget:
            name: '${self:service}-${self:custom.stage}-lambdaTestTarget'
            arn: 'arn:aws:lambda:${self:custom.region}:${self:custom.accountId}:function:${self:custom.lambda.lambdaTestTarget.name}'
    
package:
    artifact: 'target/${self:service}-${self:custom.version}.jar'

functions:
    lambdaTestSource:
        handler: 'me.wietlol.test.awslambdatests.handlers.LambdaInvokeTestHandler::source'
        environment:
            functionArn: '${self:custom.lambda.lambdaTestTarget.arn}'
    
    lambdaTestTarget:
        handler: 'me.wietlol.test.awslambdatests.handlers.LambdaInvokeTestHandler::target'
